# Generated by Django 6.0.3 on 2026-03-12 20:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hostels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_code', models.CharField(max_length=40)),
                ('full_name', models.CharField(max_length=120)),
                ('guardian_name', models.CharField(blank=True, max_length=120)),
                ('id_number', models.CharField(blank=True, max_length=64)),
                ('phone', models.CharField(max_length=20)),
                ('emergency_contact', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('joining_date', models.DateField(default=django.utils.timezone.localdate)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='male', max_length=16)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('checked_out', 'Checked Out')], default='active', max_length=20)),
                ('leaving_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='members', to='hostels.hostel')),
            ],
            options={
                'ordering': ['full_name'],
                'indexes': [models.Index(fields=['hostel', 'status'], name='members_mem_hostel__75d240_idx'), models.Index(fields=['hostel', 'phone'], name='members_mem_hostel__c71664_idx')],
                'constraints': [models.UniqueConstraint(fields=('hostel', 'member_code'), name='uniq_member_code_per_hostel'), models.UniqueConstraint(condition=models.Q(('id_number', ''), _negated=True), fields=('hostel', 'id_number'), name='uniq_member_id_number_per_hostel')],
            },
        ),
    ]
