# Generated by Django 6.0.3 on 2026-03-12 20:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hostels', '0001_initial'),
        ('members', '0001_initial'),
        ('rooms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomAllotment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed')], default='active', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allotments', to='rooms.bed')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_allotments', to=settings.AUTH_USER_MODEL)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allotments', to='hostels.hostel')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allotments', to='members.member')),
            ],
            options={
                'ordering': ['-start_date', '-id'],
                'indexes': [models.Index(fields=['hostel', 'status'], name='allotments__hostel__249c8e_idx'), models.Index(fields=['member', 'status'], name='allotments__member__41eab9_idx'), models.Index(fields=['bed', 'status'], name='allotments__bed_id_166610_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('member',), name='uniq_active_allotment_per_member'), models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('bed',), name='uniq_active_allotment_per_bed'), models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='allotment_end_date_after_start')],
            },
        ),
    ]
